In [1]:
import os

print(os.getcwd())

C:\Users\Mohit\Documents

In [2]:
import os

for file in os.listdir():
    print(file)

.ipynb_checkpoints
backpacks.csv
Basic_Data_Cleaning.ipynb
bath-robe.csv
bath-towels.csv
bathroom-accessories.csv
bedsheets.csv
belts.csv
bodysuit.csv
boots.csv
boxers.csv
bra.csv
bracelet.csv
briefs.csv
camisoles.csv
candle-holders.csv
caps.csv
casual-shoes.csv
chair-cover.csv
clothing-set.csv
clutches.csv
co-ords.csv
Combined_dataset.csv
Copy of Copy of Online Retail.csv
curtains-and-sheers.csv
Custom Office Templates
cutlery.csv
data visualization with python.pdf
deloitte data analytics simulation.pdf
desktop.ini
dinnerware.csv
dresses.csv
duffel-bag.csv
dungarees.csv
dupatta.csv
earrings.csv
ethnic-dresses.csv
face-moisturisers.csv
face-wash-and-cleanser.csv
flats.csv
flip-flops.csv
floor-mats--dhurries.csv
formal-shoes.csv
foundation.csv
gloves.csv
hair-accessory.csv
hair-brush-and-comb.csv
hair-cream-and-mask.csv
hair-masks.csv
handbags.csv
headphones.csv
heels.csv
home-fragrance-set.csv
innerwear-vests.csv
ipl_clean.pbix
jackets.csv
jeans.csv
jumpsuit.csv
JU_Sample_Minor_Project_Report.docx
kurta-sets.csv
kurtas.csv
kurtis.csv
lipstick.csv
lounge-pants.csv
lounge-shorts.csv
lounge-tshirts.csv
machine learning with python.pdf
machine learning with R.pdf
mangalsutra.csv
mobile-accessories.csv
My Music
My Pictures
My Tableau Repository
My Videos
night-suits.csv
nightdress.csv
OneNote Notebooks
outdoor-masks.csv
palazzos.csv
perfume-and-body-mist.csv
pillow-covers.csv
Power BI Desktop
practice.html
README.md
Retail_Data_Response.csv
Retail_Data_Transactions.csv
ring.csv
runners.csv
Sales Data Analysis and Reporting for Retail Chain.pptx
Sample - Superstore.csv
sandals.csv
saree-blouse.csv
sarees.csv
scarves.csv
shampoo-and-conditioner.csv
shaving-essentials.csv
sherwani.csv
shirts.csv
shorts.csv
showpieces.csv
skirts.csv
sports-shoes.csv
sunglasses.csv
sweaters.csv
sweatshirts.csv
swim-tops.csv
Synopsis FORMAT.docx.txt
table-covers.csv
thermal-bottoms.csv
tights.csv
tops.csv
towel-set.csv
track-pants.csv
trolley-bag.csv
trousers.csv
trunk.csv
TS3 LS(U) 4FEB25.docx
tshirts.csv
tunics.csv
wall-art.csv
wallets.csv
watches.csv
WindowsPowerShell
yoga-mats.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("Combined_dataset.csv")

In [5]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [6]:
df.shape

(1000, 24)

In [7]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [9]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [10]:
df["discount"] = df["discount"].fillna(0)

df["what_customers_said"] = df["what_customers_said"].fillna("No Review")

df["seller_name"] = df["seller_name"].fillna("Unknown Seller")

df["videos"] = df["videos"].fillna("No Video")

df["seller_information"] = df["seller_information"].fillna("Not Available")

df["variations"] = df["variations"].fillna("No Variations")

In [11]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df[["initial_price","final_price"]].head()

   initial_price  final_price
0           3995  "₹3,995.00"
1           2899  "₹2,899.00"
2           2999  "₹2,999.00"
3           1675  "₹1,675.00"
4           2899  "₹2,899.00"

In [16]:
df["final_price"] = (
    df["final_price"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace('"', "", regex=False)
)

df["final_price"] = pd.to_numeric(df["final_price"])

In [17]:
df[["initial_price", "final_price"]].head()

   initial_price  final_price
0           3995       3995.0
1           2899       2899.0
2           2999       2999.0
3           1675       1675.0
4           2899       2899.0

In [18]:
df["discount_amount"] = df["initial_price"] - df["final_price"]

In [19]:
df[["initial_price","final_price","discount_amount"]].head()

   initial_price  final_price  discount_amount
0           3995       3995.0              0.0
1           2899       2899.0              0.0
2           2999       2999.0              0.0
3           1675       1675.0              0.0
4           2899       2899.0              0.0

In [20]:
df.to_csv("cleaned_shopping.csv", index=False)

print("Dataset saved successfully")

Dataset saved successfully

# Basic Data Exploration and Cleaning using Pandas

## Objective
Learn Python basics and perform basic data exploration and cleaning using Pandas.

## Tasks Performed

- Loaded Combined_dataset.csv into a Pandas DataFrame.
- Explored data using head(), tail(), shape, columns and info().
- Identified missing values using isnull().
- Filled missing values appropriately.
- Removed duplicate records.
- Selected and filtered relevant columns.
- Created a derived column named discount_amount.
- Saved the cleaned dataset as cleaned_shopping.csv.

## Conclusion

The dataset was successfully cleaned and prepared for further analysis using Pandas.

In [23]:
import os

print(os.listdir())

['.ipynb_checkpoints', 'backpacks.csv', 'Basic_Data_Cleaning.ipynb', 'bath-robe.csv', 'bath-towels.csv', 'bathroom-accessories.csv', 'bedsheets.csv', 'belts.csv', 'bodysuit.csv', 'boots.csv', 'boxers.csv', 'bra.csv', 'bracelet.csv', 'briefs.csv', 'camisoles.csv', 'candle-holders.csv', 'caps.csv', 'casual-shoes.csv', 'chair-cover.csv', 'cleaned_shopping.csv', 'clothing-set.csv', 'clutches.csv', 'co-ords.csv', 'Combined_dataset.csv', 'Copy of Copy of Online Retail.csv', 'curtains-and-sheers.csv', 'Custom Office Templates', 'cutlery.csv', 'data visualization with python.pdf', 'deloitte data analytics simulation.pdf', 'desktop.ini', 'dinnerware.csv', 'dresses.csv', 'duffel-bag.csv', 'dungarees.csv', 'dupatta.csv', 'earrings.csv', 'ethnic-dresses.csv', 'face-moisturisers.csv', 'face-wash-and-cleanser.csv', 'flats.csv', 'flip-flops.csv', 'floor-mats--dhurries.csv', 'formal-shoes.csv', 'foundation.csv', 'gloves.csv', 'hair-accessory.csv', 'hair-brush-and-comb.csv', 'hair-cream-and-mask.csv', 'hair-masks.csv', 'handbags.csv', 'headphones.csv', 'heels.csv', 'home-fragrance-set.csv', 'innerwear-vests.csv', 'ipl_clean.pbix', 'jackets.csv', 'jeans.csv', 'jumpsuit.csv', 'JU_Sample_Minor_Project_Report.docx', 'kurta-sets.csv', 'kurtas.csv', 'kurtis.csv', 'lipstick.csv', 'lounge-pants.csv', 'lounge-shorts.csv', 'lounge-tshirts.csv', 'machine learning with python.pdf', 'machine learning with R.pdf', 'mangalsutra.csv', 'mobile-accessories.csv', 'My Music', 'My Pictures', 'My Tableau Repository', 'My Videos', 'night-suits.csv', 'nightdress.csv', 'OneNote Notebooks', 'outdoor-masks.csv', 'palazzos.csv', 'perfume-and-body-mist.csv', 'pillow-covers.csv', 'Power BI Desktop', 'practice.html', 'README.md', 'Retail_Data_Response.csv', 'Retail_Data_Transactions.csv', 'ring.csv', 'runners.csv', 'Sales Data Analysis and Reporting for Retail Chain.pptx', 'Sample - Superstore.csv', 'sandals.csv', 'saree-blouse.csv', 'sarees.csv', 'scarves.csv', 'shampoo-and-conditioner.csv', 'shaving-essentials.csv', 'sherwani.csv', 'shirts.csv', 'shorts.csv', 'showpieces.csv', 'skirts.csv', 'sports-shoes.csv', 'sunglasses.csv', 'sweaters.csv', 'sweatshirts.csv', 'swim-tops.csv', 'Synopsis FORMAT.docx.txt', 'table-covers.csv', 'thermal-bottoms.csv', 'tights.csv', 'tops.csv', 'towel-set.csv', 'track-pants.csv', 'trolley-bag.csv', 'trousers.csv', 'trunk.csv', 'TS3 LS(U) 4FEB25.docx', 'tshirts.csv', 'tunics.csv', 'wall-art.csv', 'wallets.csv', 'watches.csv', 'WindowsPowerShell', 'yoga-mats.csv']

In [24]:
df["discount_amount"].describe()

count     1000.000000
mean      1017.145000
std       1393.966867
min          0.000000
25%          0.000000
50%        659.000000
75%       1476.250000
max      14652.000000
Name: discount_amount, dtype: float64

In [25]:
high_rated = df[df["rating"] > 4]

high_rated.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,discount_amount
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,0.0
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,1399.0,INR,http://assets.myntassets.com/assets/images/171...,...,No Review,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",No Video,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories,0.0

In [26]:
high_rated = df[df["rating"] > 4]

print("Number of high-rated products:", len(high_rated))

high_rated.head()

Number of high-rated products: 533

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,discount_amount
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,0.0
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,1399.0,INR,http://assets.myntassets.com/assets/images/171...,...,No Review,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",No Video,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories,0.0

In [27]:
# Column Selection
df[["title", "final_price", "rating"]].head()

            title  final_price  rating
0     Lino Perros       3995.0     3.8
1  Tommy Hilfiger       2899.0     4.5
2           Lavie       2999.0     4.4
3          F Gear       1675.0     4.4
4       MYTRIDENT       2899.0     4.7

In [28]:
# Filtering
high_rated = df[df["rating"] > 4]
high_rated.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,discount_amount
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,0.0
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,1399.0,INR,http://assets.myntassets.com/assets/images/171...,...,No Review,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",No Video,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories,0.0

In [29]:
# Export
df.to_csv("cleaned_shopping.csv", index=False)

In [30]:
import os

required_files = [
    "Basic_Data_Cleaning.ipynb",
    "Combined_dataset.csv",
    "cleaned_shopping.csv",
    "README.md"
]

for file in required_files:
    if os.path.exists(file):
        print(f"✅ {file} found")
    else:
        print(f"❌ {file} NOT found")

✅ Basic_Data_Cleaning.ipynb found
✅ Combined_dataset.csv found
✅ cleaned_shopping.csv found
✅ README.md found